export const FETCH_POSTS_REQUEST = "FETCH_POSTS"
export const FETCH_POSTS_SUCCEED = "FETCH_POSTS_SUCCEED"
export const FETCH_SINGLE_POST_REQUEST = "FETCH_SINGLE_POST"
export const FETCH_SINGLE_POST_SUCCEED = "FETCH_SINGLE_POST_SUCCEED" 